language: python
python:
- '2.7'
sudo: true
dist: trusty
before_install:
- sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-font-utils texlive-generic-recommended purifyeps
script:
- (cd sheets; LATEX_OPTS="-interaction=nonstopmode -shell-escape" make pdfrelease)
deploy:
  provider: releases
  api_key:
    secure: cONhoGDyJTI1AB3N52EXNKoP6VivURket/NZEIzEpLgg2iiXzvevTZehOIJmdB67fdW0cHqkgpsD2kxxJ/BkoJN7atOPdmnIOeKD2GX8ntT33Fcvs3Co2drVPLtpriWQhnY7qNVBsYpm4kuyRZ+gAjFkQus6JC3+YF+O3U29lGTR/CFBmZMgIR+LLUVZMOYlugAOe/6aIYAKhw7jG2B4Do1s/gPM/l9fexqYr5B+4iiTRDZgDo9PcwhyzTEU7XsHhEHf3JQWxWE5U1XybBvvb826EIEj3ak/TaTvF5xe2uIuTGU9Hx5GAvJEOjuB3s/WAhVTGLm50y58ipmLiTg54Ya6tkdLZzsArX+wAexjW58kAlGDiFIvQcmvcdbLBfgtnlAR7MsZEksaJ5TWVZohGMAK0+umIlmJ7sqnQu2g5x11BxAM2TEW5TyTTtlQL1u4Tbc11UGCkVdzqPTBrEJis0b7WTrWawpDlqi22GXeHPl2jI372TMXT5crdIZAgC1zJdF7B+cpxE2bJLrm4JUnAqKtZWs/nmwKMDZ0Z5kG9AtL9aFQhgCr3C7SG+f6HBTiylYRZtucrXWzjU7r8vU9Bc64efvcQr/KFFo9xjLxDRpEyG0t/0q3LUKQdrDpNdVmMXJqYL/cWLHqEoev+LngeIuRhpvX9eeqXdaR0p+E688=
  file: release/livewires-pdfs.tar.gz
  skip_cleanup: true
  on:
    repo: livewires/python
    tags: true

